# -*- coding: utf-8 -*-
"""CVAssignment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gUMQKYIHwt8tT3U_uV4EjZ9crC1MBk2Y
"""

import cv2
import numpy as np
import random
import matplotlib.pyplot as plt

# Load images
left_img = cv2.imread('1.jpg')
right_img = cv2.imread('2.jpg')


# Plot original images
plt.figure(figsize=(10, 5))
plt.subplot(1, 2, 1)
plt.imshow(cv2.cvtColor(left_img, cv2.COLOR_BGR2RGB))
plt.title('Original Left Image')
plt.axis('off')

plt.subplot(1, 2, 2)
plt.imshow(cv2.cvtColor(right_img, cv2.COLOR_BGR2RGB))
plt.title('Original Right Image')
plt.axis('off')
plt.show()

# Convert images to grayscale
l_img = cv2.cvtColor(left_img, cv2.COLOR_BGR2GRAY)
r_img = cv2.cvtColor(right_img, cv2.COLOR_BGR2GRAY)


# Plot grayscale images
plt.figure(figsize=(10, 5))
plt.subplot(1, 2, 1)
plt.imshow(l_img, cmap='gray')
plt.title('Grayscale Left Image')
plt.axis('off')

plt.subplot(1, 2, 2)
plt.imshow(r_img, cmap='gray')
plt.title('Grayscale Right Image')
plt.axis('off')
plt.show()

# Create SIFT object
sift = cv2.SIFT_create()

# Detect and compute keypoints and descriptors
key_points1, descriptor1 = sift.detectAndCompute(l_img, None)
key_points2, descriptor2 = sift.detectAndCompute(r_img, None)

# Draw keypoints on both images
keypoints_img1 = cv2.drawKeypoints(l_img, key_points1, None, flags=cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)
keypoints_img2 = cv2.drawKeypoints(r_img, key_points2, None, flags=cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)

# Plot keypoints on both images
plt.figure(figsize=(10, 5))
plt.subplot(1, 2, 1)
plt.imshow(cv2.cvtColor(keypoints_img1, cv2.COLOR_BGR2RGB))
plt.title('Keypoints Left Image')
plt.axis('off')

plt.subplot(1, 2, 2)
plt.imshow(cv2.cvtColor(keypoints_img2, cv2.COLOR_BGR2RGB))
plt.title('Keypoints Right Image')
plt.axis('off')
plt.show()

#Match keypoints using Brute Force Matcher with SIFT-specific norm
bf = cv2.BFMatcher(cv2.NORM_L2, crossCheck=True)

matches = bf.match(descriptor1, descriptor2)

# Sort matches by distance
matches = sorted(matches, key=lambda x: x.distance)

# Select good matches (top 40%)
good_matches = matches[:int(len(matches) * 0.4)]

# Draw good matches between the two images
matches_img = cv2.drawMatches(l_img, key_points1, r_img, key_points2, good_matches, None, flags=cv2.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS)

# Plot matched keypoints
plt.figure(figsize=(10, 5))
plt.imshow(cv2.cvtColor(matches_img, cv2.COLOR_BGR2RGB))
plt.title('Matched Keypoints')
plt.axis('off')
plt.show()

# Function to compute homography using RANSAC
def ransac_homography(good_points, iterations=5000, threshold=5):
    best_inliers = []
    final_H = None

    for _ in range(iterations):
        # Randomly choose 4 points to compute homography
        random_pts = random.sample(good_points, 4)

        # Compute homography matrix H using the chosen points
        A = []
        for pt in random_pts:
            x, y, X, Y = pt
            A.append([x, y, 1, 0, 0, 0, -X * x, -X * y, -X])
            A.append([0, 0, 0, x, y, 1, -Y * x, -Y * y, -Y])
        A = np.array(A)
        _, _, vh = np.linalg.svd(A)
        H = vh[-1, :].reshape(3, 3)
        H = H / H[2, 2]  # Normalize

        # Count inliers by comparing the homography transformation
        inliers = []
        for pt in good_points:
            p = np.array([pt[0], pt[1], 1]).reshape(3, 1)
            p_1 = np.array([pt[2], pt[3], 1]).reshape(3, 1)
            Hp = np.dot(H, p)
            Hp = Hp / Hp[2]
            dist = np.linalg.norm(p_1 - Hp)
            if dist < threshold:
                inliers.append(pt)

        # Update best homography if more inliers are found
        if len(inliers) > len(best_inliers):
            best_inliers = inliers
            final_H = H

    return final_H, len(best_inliers)

# Example usage with matched points from images:
good_points = []
for match in good_matches:
    p1 = key_points1[match.queryIdx].pt
    p2 = key_points2[match.trainIdx].pt
    good_points.append([p1[0], p1[1], p2[0], p2[1]])

# Compute homography using RANSAC
final_H, num_inliers = ransac_homography(good_points)

# Output the final homography matrix and the number of inliers
print("Final Homography Matrix:\n", final_H)
print("Number of Inliers:", num_inliers)

# Prepare for warping
rows1, cols1 = right_img.shape[:2]
rows2, cols2 = left_img.shape[:2]

points1 = np.float32([[0, 0], [0, rows1], [cols1, rows1], [cols1, 0]]).reshape(-1, 1, 2)
points = np.float32([[0, 0], [0, rows2], [cols2, rows2], [cols2, 0]]).reshape(-1, 1, 2)
points2 = cv2.perspectiveTransform(points, final_H)
list_of_points = np.concatenate((points1, points2), axis=0)

[x_min, y_min] = np.int32(list_of_points.min(axis=0).ravel() - 0.5)
[x_max, y_max] = np.int32(list_of_points.max(axis=0).ravel() + 0.5)

H_translation = np.dot(np.array([[1, 0, -x_min], [0, 1, -y_min], [0, 0, 1]]), final_H)

# Warp the left image
output_img = cv2.warpPerspective(left_img, H_translation, (x_max - x_min, y_max - y_min))

# Place right image onto the warped left image
output_img[-y_min:rows1 - y_min, -x_min:cols1 - x_min] = right_img

# Plot the warped image
plt.figure(figsize=(10, 10))
plt.imshow(cv2.cvtColor(output_img, cv2.COLOR_BGR2RGB))
plt.title('Final Stitched Image')
plt.axis('off')
plt.show()

