# -*- coding: utf-8 -*-
"""cvAssignment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pxPenI_Pg-8TZfRQ5qArofpy_a_3Mf3P
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Load the image
image_path = 'WhatsApp Image 2025-01-24 at 10.35.47.jpeg'
image = cv2.imread(image_path)

# Convert the image to grayscale
gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Define the checkerboard pattern size (Columns, Rows)
pattern_size = (6, 8)

# Detect the checkerboard corners in the grayscale image
ret, corners = cv2.findChessboardCorners(gray_image, pattern_size, None)

# If corners are found, draw and display them
if ret:
    cv2.drawChessboardCorners(image, pattern_size, corners, True)  # Draw on the original image

    # Display the image directly in the notebook
    plt.figure(figsize=(10, 6))
    plt.imshow(image)  # No RGB conversion needed
    plt.title('Output Image with Detected Corners')
    plt.axis('off')
    plt.show()

    # Print the 2D coordinates of each detected corner
    print("Found Corners (2D Image Coordinates):")
    for i, corner in enumerate(corners):
        x, y = corner[0]  # Extract (x, y) coordinates
        print(f"Corner {i + 1}: ({x:.2f}, {y:.2f})")
else:
    print("Checkerboard corners not found!")

"""+ This code detects and visualizes checkerboard corners in an image, which is essential for camera calibration.
+ It starts by loading the image and defining the checkerboard pattern size with the number of inner corners along the columns and rows.
+  Using OpenCV's findChessboardCorners() function, it attempts to locate these corners, returning their 2D coordinates if detected.
+  If successful, the detected corners are drawn on the image using drawChessboardCorners()
+  The code then prints the (x, y) coordinates of each detected corner. If the pattern isn't found, it displays a message indicating the failure. This process ensures both visual feedback and coordinate extraction, which are crucial steps in calibrating the intrinsic and extrinsic parameters of a camera.
"""

square_size = 30  # size of each square in mm
distance_camera_to_checkerboard = 300  # in mm

# Calculate the 3D world coordinates (absolute coordinates based on fixed camera distance)
world_points_fixed_distance = []

for row in range(pattern_size[1]):
    for col in range(pattern_size[0]):
        x = col * square_size
        y = row * square_size
        z = np.sqrt(max(0, distance_camera_to_checkerboard**2 - x**2 - y**2))
        world_points_fixed_distance.append([x, y, z])

world_points_fixed_distance = np.array(world_points_fixed_distance, dtype=np.float32)

print("\n3D World Coordinates with Fixed Distance (in mm):\n", world_points_fixed_distance)

"""+ This code calculates the 3D world coordinates of the checkerboard corners based on a fixed camera distance.
+ The size of each square on the checkerboard is specified in millimeters (square_size = 30), and the distance from the camera to the checkerboard is set to 300 mm.
+  The coordinates are generated by iterating over the rows and columns of the pattern, with x and y values computed as multiples of the square size.
+  The z-coordinate is calculated using the Pythagorean theorem to maintain the fixed distance from the camera, ensuring that z= sqrt(300^2-X^2-Y^2).
+ This results in a list of 3D coordinates, representing the corners in real-world space, which are then stored as a NumPy array. These 3D points are essential for camera calibration to map 2D image points to real-world coordinates.
"""

# Define the reference point (bottom-left corner)
reference_point = np.array([0, 0, distance_camera_to_checkerboard], dtype=np.float32)

# Calculate world coordinates relative to the reference point (bottom-left corner)
world_points_relative = []

for row in range(pattern_size[1]):
    for col in range(pattern_size[0]):
        x = col * square_size
        y = row * square_size
        z = reference_point[2]  # Keep Z as the fixed distance for the reference point

        # Subtract the reference point position from the current world point
        world_point_relative = np.array([x, y, z], dtype=np.float32) - reference_point
        world_points_relative.append(world_point_relative)

world_points_relative = np.array(world_points_relative, dtype=np.float32)

# Print the 3D world coordinates relative to the bottom-left reference point
print("\n3D World Coordinates Relative to Bottom-Left Corner (in mm):\n", world_points_relative)

"""+ This code computes the 3D world coordinates of the checkerboard corners relative to a reference point, defined as the bottom-left corner of the checkerboard with a fixed distance from the camera.
+  The reference point is [0, 0, 300] mm, where 300 mm is the distance from the camera to the checkerboard.
+ For each corner, the x and y coordinates are calculated by multiplying the row and column indices with the square size (30 mm).
+  The z-coordinate is fixed at the reference distance (300 mm). Each corner’s coordinate is then adjusted by subtracting the reference point to yield its relative position in the 3D space.
+ The final result is stored in a NumPy array and printed. These coordinates are useful for tasks like calibration, where knowing the relative position of points is crucial.
"""

# Proceed if corners were successfully detected
if ret:
    # Prepare the data for calibration
    object_points = [world_points_fixed_distance]  # List of object points (3D points in the world)
    image_points = [corners.reshape(-1, 2)]  # List of corresponding image points (2D points in the image)
    image_size = (gray_image.shape[1], gray_image.shape[0])

    # Provide an initial guess for the intrinsic matrix
    fx = image_size[0]  # Focal length in pixels along x-axis
    fy = image_size[1]  # Focal length in pixels along y-axis
    cx = image_size[0] / 2  # Principal point (center of the image) along x-axis
    cy = image_size[1] / 2  # Principal point (center of the image) along y-axis

    # Create the initial intrinsic matrix
    initial_intrinsic_matrix = np.array([
        [fx, 0, cx],
        [0, fy, cy],
        [0, 0, 1]
    ], dtype=np.float32)

    # Calibrate the camera with the initial intrinsic guess
    ret, intrinsic_matrix, dist_coeffs, rvecs, tvecs = cv2.calibrateCamera(
        object_points, image_points, image_size, initial_intrinsic_matrix, None, flags=cv2.CALIB_USE_INTRINSIC_GUESS
    )

    if ret:
        # Convert rotation vector to rotation matrix
        rotation_matrix, _ = cv2.Rodrigues(rvecs[0])
        translation_vector = tvecs[0]

        # Construct the extrinsic matrix [R | t]
        extrinsic_matrix = np.hstack((rotation_matrix, translation_vector))

        # Compute the projection matrix: A * [R | t]
        projection_matrix = intrinsic_matrix @ extrinsic_matrix

        # Display the matrices
        print("\nIntrinsic Matrix (A):\n", intrinsic_matrix)
        print("\nRotation Matrix (R):\n", rotation_matrix)
        print("\nTranslation Vector (t):\n", translation_vector)
        print("\nExtrinsic Matrix [R | t]:\n", extrinsic_matrix)
        print("\nProjection Matrix (A * [R | t]):\n", projection_matrix)
    else:
        print("Camera calibration failed!")
else:
    print("Checkerboard corners not found!")

"""+ This code performs camera calibration using detected checkerboard corners to compute the intrinsic matrix, extrinsic matrix, and projection matrix.
+ It first prepares the 3D world coordinates (object points) and their corresponding 2D image points.
+ An initial intrinsic matrix guess is provided, containing the camera’s focal length and principal point. Using cv2.calibrateCamera(), the code refines this matrix and outputs the rotation and translation vectors.
+ The rotation vector is converted into a rotation matrix, and combined with the translation vector to form the extrinsic matrix, representing the camera’s orientation and position in the world.
+ The final projection matrix is obtained by multiplying the intrinsic matrix with the extrinsic matrix, which maps 3D world points to 2D image coordinates. If calibration is successful, it prints the matrices; otherwise, it displays an error message.
"""