# -*- coding: utf-8 -*-
"""singular_from_motion_(1)_(1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1caU1zkZY3jtGU5tSTxWv0IDzaLhAgaot
"""

import cv2
import numpy as np
import cv2
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from scipy.linalg import svd

def main(video_path):
    # Extract frames
    def extract_frames(video_path):
        cap = cv2.VideoCapture(video_path) #OpenCV function that reads the video file.
        if not cap.isOpened(): #Check if the video file was successfully opened
            print("Error: Could not open video.")
            exit()
        frames = []
        while cap.isOpened():
            ret, frame = cap.read() #Read video frames one by one & cap.read() reads the next frame of the video.
            if not ret:
                break
            frames.append(cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)) #in this step it converts into grayscale then stored in a new list
        cap.release() #Release the video capture object.
        if len(frames) < 2: #Ensure there are enough frames to process (at least two frames are required for motion tracking)
            print("Not enough frames for processing.")
            exit()
        print(f"Total number of frames: {len(frames)}")
        return frames


    # Track points using Lucas-Kanade Tracker
    def track_points(frames):
        lk_params = dict(winSize=(21, 21), maxLevel=3, #Define parameters for the Lucas-Kanade Tracker (LKT)
                        criteria=(cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_COUNT, 15, 0.01))

        # Initialize the first frame as the reference
        #Detect good features to track (like corners) in the first frame.
        initial_points = cv2.goodFeaturesToTrack(frames[0], mask=None, maxCorners=200, qualityLevel=0.01, minDistance=5, blockSize=5)
        if initial_points is None:
            print("No features detected in the first frame.")
            exit()

        tracked_points = [initial_points.reshape(-1, 2)] #reshapuing the tracked points
        '''The initial_points array returned by cv2.goodFeaturesToTrack is typically of shape:(n,1,2)
n: Number of points detected.
1: Extra dimension for compatibility (not needed here).
2: Represents the (x,y)coordinates of each point.
In this we are removing second demension i.e. 1 & the reshaping simplies the array to (n,2) it directly represents the(x,y) coordinates of the n points'''
        valid_mask = np.ones((initial_points.shape[0],), dtype=bool) #A mask to keep track of successfully tracked points

        for i in range(1, len(frames)): #Iterates over all consecutive frames in the frames list, starting from the second frame (i=1).
            points_prev_frame = tracked_points[-1] #Retrieves the feature points (x,y) tracked from the previous frame.
            points_next_frame, st, err = cv2.calcOpticalFlowPyrLK(frames[i - 1], frames[i], points_prev_frame, None, **lk_params)
     #Tracks the motion of feature points from the previous frame (frames[i - 1]) to the current frame (frames[i]) using the Lucas-Kanade optical flow algorithm.

            valid_mask &= (st.flatten() == 1)
            tracked_points.append(points_next_frame) #adds the tracked points from the current frame (points_next_frame) to the tracked_points list

        filtered_points = [frame_points[valid_mask] for frame_points in tracked_points] #Filters out points that were not successfully tracked in all frames, leaving only valid points.
        print(f"Number of successfully tracked points: {len(filtered_points[0])}")
        return filtered_points

    # Compute Q matrix, M, and S
    def compute_Q(points):
        frames = len(points)  # Number of frames by counting length of points list
        #Determines how many points were successfully tracked in a single frame.
        points_per_frame = points[0].shape[0]  # Number of points per frame
        W = np.zeros((2 * frames, points_per_frame)) # Initializes the measurement matrix W, which will store the (x,y) coordinates of the tracked points for all frames.

        for i, frame_points in enumerate(points): #Iterates over the points list to process each frame's tracked points.
            W[2 * i, :] = frame_points[:, 0]  # store the  x-coordinate values of the points for the current frame into the appropriate row of W
            W[2 * i + 1, :] = frame_points[:, 1]  # store the y-coordinate values of the points for the current frame into the appropriate row of W
#Computes the mean of each row in W

        W -= np.mean(W, axis=1, keepdims=True)  #Centers the data in W by subtracting the mean of each row
        # Perform SVD
        U, Sigma, VT = np.linalg.svd(W, full_matrices=False)
        '''Perform Singular Value Decomposition (SVD) on W, where:
U: Motion matrix.
Σ: Singular values (diagonal matrix).
VT : Structure matrix.
SVD decomposes W into orthogonal components for dimensionality reduction.'''

        # Reduce to rank-3 approximation
        U_reduced = U[:, :3] #Selects the first 3 columns of U to reduce the dimensionality of the data
        Sigma_reduced = np.diag(Sigma[:3]) #Constructs a reduced diagonal matrix containing only the top 3 singular values.
        VT_reduced = VT[:3, :] #Selects the first 3 rows of VT, corresponding to the top 3 singular values

        # Compute M and S matrices
        M = np.dot(U_reduced, Sigma_reduced)
        S = VT_reduced

        return M, S

    # Main Process
    frames = extract_frames(video_path) #Extract frames from the video.
    points = track_points(frames)#Track feature points across frames.

    # Compute Q matrix
    M, S = compute_Q(points) #Compute M, S, and reconstruct Q, the rank-3 approximation of the measurement matrix.
    Q = np.dot(M, S)

    print("\nQ Matrix (Reconstructed Measurement Matrix):")
    print(Q)
    print("\nMotion Matrix M:")
    print(M)
    print("\nStructure Matrix S:")
    print(S)

# Provide the path to your video file
video_path = "/content/WhatsApp Video 2025-01-22 at 12.29.17.mp4"
main(video_path)